export const dessertTableData = [
  {
    dessert: "Frozen yougurt",
    calories: 159,
    fat: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    calcium: "14%",
    iron: "1%",
    id: 1,
  },
  {
    dessert: "Ice cream sandwich",
    calories: 237,
    fat: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    calcium: "8%",
    iron: "1%",
    id: 2,
  },
  {
    dessert: "Eclair",
    calories: 262,
    fat: 16.0,
    carbs: 24,
    protein: 6.0,
    sodium: 337,
    calcium: "6%",
    iron: "7%",
    id: 3,
  },
  {
    dessert: "Cupcake",
    calories: 305,
    fat: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    calcium: "3%",
    iron: "8%",
    id: 4,
  },
  {
    dessert: "Gingerbread",
    calories: 356,
    fat: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    calcium: "7%",
    iron: "16%",
    id: 5,
  },
  {
    dessert: "Jelly Bean",
    calories: 375,
    fat: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    calcium: "0%",
    iron: "2%",
    id: 6,
  },
  {
    dessert: "Lollipop",
    calories: 392,
    fat: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    calcium: "0%",
    iron: "2%",
    id: 7,
  },
  {
    dessert: "Honeycomb",
    calories: 408,
    fat: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    calcium: "0%",
    iron: "45%",
    id: 8,
  },
  {
    dessert: "Dount",
    calories: 452,
    fat: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    calcium: "2%",
    iron: "22%",
    id: 9,
  },
  {
    dessert: "KitKat",
    calories: 518,
    fat: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    calcium: "12%",
    iron: "6%",
    id: 10,
  },
];

export const AcademicTableData = [
  {
    compSub: "FIRST LANGUAGE",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 63,
    mOral: 10,
    mTotal: 73,
    mGrade: "A",
  },
  {
    compSub: "SECOND LANGUAGE",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 53,
    mOral: 9,
    mTotal: 62,
    mGrade: "A",
  },
  {
    compSub: "MATHEMATICS",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 76,
    mOral: 9,
    mTotal: 85,
    mGrade: "A+",
  },
  {
    compSub: "PHYSICAL SCIENCE",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 89,
    mOral: 7,
    mTotal: 96,
    mGrade: "AA",
  },
  {
    compSub: "LIFE SCIENCE",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 85,
    mOral: 5,
    mTotal: 80,
    mGrade: "AA",
  },
  {
    compSub: "HISTORY",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 63,
    mOral: 9,
    mTotal: 72,
    mGrade: "A",
  },
  {
    compSub: "GEOGRAPHY",
    fwritten: 90,
    fOral: 10,
    fTotal: 100,
    mWritten: 75,
    mOral: 10,
    mTotal: 85,
    mGrade: "A+",
  },
  {
    compSub: "OPIONAL SUBJECT",
    fTotal: 100,
  },
];
